name: docker-compose

on: [push, pull_request]

jobs:
  Integration-test:

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: Set up AWX
        uses: Tompage1994/github-actions/awx@awx-test
        with:
          version: 13.0.0
          test-script: .github/workflows/test-script.sh